# Generated by Django 2.0.6 on 2019-05-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('detail_address', models.CharField(max_length=40)),
                ('zipcode', models.CharField(max_length=20)),
                ('telphone', models.CharField(blank=True, max_length=40, null=True)),
                ('addr_mobile', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('book_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=128, null=True)),
                ('book_author', models.CharField(blank=True, max_length=64, null=True)),
                ('book_publish', models.CharField(blank=True, max_length=128, null=True)),
                ('publish_time', models.DateField(blank=True, null=True)),
                ('revision', models.IntegerField(blank=True, null=True)),
                ('book_isbn', models.CharField(blank=True, max_length=64, null=True)),
                ('word_count', models.CharField(blank=True, max_length=64, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('book_paper', models.CharField(blank=True, max_length=64, null=True)),
                ('book_wrapper', models.CharField(blank=True, max_length=64, null=True)),
                ('book_price', models.FloatField(blank=True, null=True)),
                ('book_dprice', models.FloatField(blank=True, null=True)),
                ('series_name', models.CharField(blank=True, max_length=64, null=True)),
                ('printing_time', models.DateField(blank=True, null=True)),
                ('impression', models.CharField(blank=True, max_length=64, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('shelves_date', models.DateField(blank=True, null=True)),
                ('customer_socre', models.CharField(blank=True, max_length=64, null=True)),
                ('book_status', models.CharField(blank=True, max_length=64, null=True)),
                ('sales', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TCategory',
            fields=[
                ('idcategory_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=40)),
                ('book_counts', models.CharField(blank=True, max_length=40, null=True)),
                ('category_pid', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('num', models.CharField(blank=True, max_length=40, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TOrderitem',
            fields=[
                ('shop_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('shop_num', models.CharField(max_length=40)),
                ('total_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_orderitem',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, max_length=40, null=True)),
                ('user_name', models.CharField(blank=True, max_length=40, null=True)),
                ('user_password', models.CharField(blank=True, max_length=40, null=True)),
                ('user_status', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_user',
            },
        ),
    ]
