# Generated by Django 2.0.6 on 2019-05-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_confirm_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm_string',
            old_name='user',
            new_name='users',
        ),
    ]
