# Generated by Django 2.0.6 on 2019-05-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190526_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuser',
            options={},
        ),
    ]
